# ---------------------------------------------------------
# For theme selection, add the theme extra configuration:
# jekyll serve --watch --config _config.yml,./_themes/striped/_config.yml
# (theme are located in the ./_themes/ directory)
# ---------------------------------------------------------

# ---------------------------------------------------------
# Blog configuration
# ---------------------------------------------------------
# Site name
name: Don Quiblog

# Number of posts per page on index
paginate: 2

# Only use this variable when absolutely necessary (sitemap.txt)
production_url : http://prettystack.com/striped/jekyll


# ---------------------------------------------------------
# Third party services configuration
# ---------------------------------------------------------
# Disqus conf, comment these lines to disable Disqus
disqus:
  shortname: donquiblog


# ---------------------------------------------------------
# Jekyll internal conf
# ---------------------------------------------------------
markdown: kramdown
pygments: true
exclude: ["readme.md", "LICENSE", "Gemfile"]
# Jekyll truncate post at this separator to provide an excerpt on index
excerpt_separator: <!--more-->
