# ---------------------------------------------------------
# Theme selection
# (theme should be installed in ./themes/ directory)
# ---------------------------------------------------------
source: ./themes/striped

# ---------------------------------------------------------
# Blog configuration
# ---------------------------------------------------------
# Site name
name: Don Quiblog

# Number of posts per page on index
paginate: 2

# Only use this variable when absolutely necessary (sitemap.txt)
production_url : http://prettystack.com/striped/jekyll


# ---------------------------------------------------------
# Third party services configuration
# ---------------------------------------------------------
# Disqus conf, comment these lines to disable Disqus
disqus:
  shortname: donquiblog


# ---------------------------------------------------------
# Assets pipeline configuration
# ---------------------------------------------------------
assets:
  dirname: assets
  baseurl: /assets/
  # js_compressor: uglifier
  # css_compressor: sass

# ---------------------------------------------------------
# Jekyll internal conf
# ---------------------------------------------------------
markdown: kramdown
pygments: true
exclude: ["readme.md", "LICENSE", "Gemfile"]
# Force standard directory for plugins and generation
destination: ./_site
plugins: ./_plugins
# Jekyll truncate post at this separator to provide an excerpt on index
excerpt_separator: <!--more-->
